on: [push]

concurrency:
  group: ${{ github.ref }}/tests
  cancel-in-progress: true

jobs:
  checks:
    name: "Code checks"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build TypeScript
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Check Foramtting
        run: yarn formatting
      - name: Test
        run: yarn test
